spring.application.name=support-web-ui

server.port=8082

support.api.base-url=http://localhost:8080

management.endpoints.web.exposure.include=health,info

vaadin.launch-browser=true
vaadin.launch-browser-delay=0