spring.application.name=support-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/support_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger
springdoc.show-actuator=false

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.name=Industrial Support Hub
info.description=Платформа управления инцидентами и автоматизации технической поддержки промышленных предприятий.
info.author=Immx

security.jwt.secret=${JWT_SECRET}
security.jwt.issuer=industrial-support-hub
security.jwt.access-token-ttl=P30D

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

app.kafka.enabled=true
app.kafka.topics.incident-events=support.incident.events.v1

app.outbox.publisher.delay=5000
app.outbox.publisher.batch-size=100
app.outbox.publisher.max-retries=5
