spring.application.name=support-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/support_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger
springdoc.show-actuator=false

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.name=Industrial Support Hub
info.description=Платформа управления инцидентами и автоматизации технической поддержки промышленных предприятий.
info.author=Immx
